"use client";
import { ArrowLeft, Check, ChefHat, Flame, Heart, RotateCcw, Share2, TicketPercent, Timer, Undo2 } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { sauceTarget, scoreCookingGame, type PlatingChoice, type SauceControl } from "@/lib/cooking-game";
import { assetUrl } from "@/lib/asset-url";
import type { TasteVector } from "@/types";

type Phase="intro"|"ingredients"|"prep"|"heat"|"seasoning"|"plating"|"result";
const INGREDIENTS=[{id:"pasta",mark:"01",name:"意大利面",note:"主食",image:"/images/cooking-game/pasta.webp"},{id:"tomato",mark:"02",name:"番茄肉酱",note:"酸香底味",image:"/images/cooking-game/tomato-sauce.webp"},{id:"beef",mark:"03",name:"牛肉粒",note:"蛋白质",image:"/images/cooking-game/beef.webp"},{id:"broccoli",mark:"04",name:"西兰花",note:"蔬菜",image:"/images/cooking-game/broccoli.webp"},{id:"cream",mark:"05",name:"厚奶油",note:"提高腻感",image:"/images/cooking-game/cream.webp"},{id:"soda",mark:"06",name:"甜汽水",note:"不入锅",image:"/images/cooking-game/soda.webp"}];
const STEPS=[{id:"sear",name:"煎香牛肉",note:"建立焦香"},{id:"boil",name:"煮面至八分熟",note:"保留弹性"},{id:"toss",name:"面与酱汁翻拌",note:"均匀挂汁"},{id:"sauce",name:"炒出番茄酱香",note:"收浓水分"}];

export function CookingGame({taste,couponClaimed,onBack,onCoupon,onToast}:{taste:TasteVector;couponClaimed?:boolean;onBack:()=>void;onCoupon:()=>void;onToast:(m:string)=>void}){
 const [phase,setPhase]=useState<Phase>("intro"),[ingredients,setIngredients]=useState<string[]>([]),[sequence,setSequence]=useState<string[]>([]),[heat,setHeat]=useState(15),[dir,setDir]=useState(1),[sauce,setSauce]=useState<SauceControl>({acid:50,salt:50,spice:30}),[plating,setPlating]=useState<PlatingChoice>("balanced"),[liked,setLiked]=useState(false);
 const score=useMemo(()=>scoreCookingGame({ingredients,sequence,heat,sauce,plating,taste}),[ingredients,sequence,heat,sauce,plating,taste]);
 useEffect(()=>{if(phase!=="heat")return;const t=window.setInterval(()=>setHeat(v=>{const n=v+dir*3;if(n>=100){setDir(-1);return 100}if(n<=5){setDir(1);return 5}return n}),70);return()=>clearInterval(t)},[phase,dir]);
 const reset=()=>{setPhase("intro");setIngredients([]);setSequence([]);setHeat(15);setDir(1);setSauce({acid:50,salt:50,spice:30});setPlating("balanced")};
 const share=async()=>{const m=`尖锋厨房挑战 ${score.total}分｜${score.title}。来试试你的火候。`;try{await navigator.clipboard.writeText(`${m} ${location.origin}${location.pathname}?game=challenge`);onToast("挑战链接已复制")}catch{onToast(m)}};
 const progress=(active:number)=><div className="game-progress">{[0,1,2,3,4].map(i=><i key={i} className={i<active?"is-done":i===active?"is-on":""}/>)}</div>;
 return <main className="cooking-game"><header className="game-top"><button onClick={onBack}><ArrowLeft size={20}/></button><span><ChefHat size={18}/><b>尖锋厨房挑战</b></span><em>CHEF TEST 01</em></header>
 {phase==="intro"&&<section className="game-intro mature"><div className="chef-pass"><span>JF / KITCHEN</span><strong>01</strong><i>番茄肉酱意面</i><em>今日主厨考核</em></div><span className="game-kicker">限时操作 · 味觉画像参与评分</span><h1>不是照着答案点。<br/>像主厨一样做判断。</h1><p>食材取舍、出餐顺序、火候和调味都会影响结果。85分以上获得厨艺礼资格。</p><div className="game-rules"><span><b>20</b>食材</span><span><b>20</b>顺序</span><span><b>25</b>火候</span><span><b>20</b>调味</span><span><b>15</b>装盘</span></div><button className="game-primary" onClick={()=>setPhase("ingredients")}>进入后厨 <Flame size={18}/></button></section>}
 {phase==="ingredients"&&<section className="game-stage">{progress(0)}<span className="game-kicker">01 / 食材取舍</span><h2>只能带4样进厨房。<br/>选错会扣浪费分。</h2><div className="ingredient-grid mature-grid">{INGREDIENTS.map(x=><button key={x.id} className={ingredients.includes(x.id)?"is-selected":""} onClick={()=>setIngredients(c=>c.includes(x.id)?c.filter(i=>i!==x.id):c.length<4?[...c,x.id]:c)}><figure><img src={assetUrl(x.image)} alt={x.name}/><i>{x.mark}</i></figure><span><b>{x.name}</b><small>{x.note}</small></span>{ingredients.includes(x.id)&&<Check size={14}/>}</button>)}</div><button className="game-primary" disabled={ingredients.length!==4} onClick={()=>setPhase("prep")}>确认备料</button></section>}
 {phase==="prep"&&<section className="game-stage">{progress(1)}<span className="game-kicker">02 / 出餐顺序</span><h2>按真实操作顺序，<br/>依次加入流程。</h2><div className="sequence-board"><div>{sequence.map((id,i)=><span key={`${id}-${i}`}><i>0{i+1}</i><b>{STEPS.find(x=>x.id===id)?.name}</b></span>)}</div><button disabled={!sequence.length} onClick={()=>setSequence(c=>c.slice(0,-1))}><Undo2 size={14}/>撤回</button></div><div className="step-pool">{STEPS.map(x=><button key={x.id} disabled={sequence.includes(x.id)} onClick={()=>setSequence(c=>[...c,x.id])}><span><b>{x.name}</b><small>{x.note}</small></span><i>+</i></button>)}</div><button className="game-primary" disabled={sequence.length!==4} onClick={()=>setPhase("heat")}>执行这套流程</button></section>}
 {phase==="heat"&&<section className="game-stage heat-stage">{progress(2)}<span className="game-kicker">03 / 火候窗口</span><h2>酱汁开始抱团时，<br/>在黄金区关火。</h2><div className="heat-visual"><div className="sauce-surface"><i/><i/><i/><span/></div><em style={{opacity:.25+heat/140}}>HEAT {heat}</em></div><div className="heat-meter"><span className="heat-zone"/><i style={{left:`${heat}%`}}/></div><div className="heat-labels"><span>未收汁</span><b>68–78 黄金区</b><span>焦苦</span></div><button className="game-primary game-fire-button" onClick={()=>setPhase("seasoning")}><Timer size={18}/>现在关火</button></section>}
 {phase==="seasoning"&&<section className="game-stage">{progress(3)}<span className="game-kicker">04 / 味觉校准</span><h2>没有标准答案。<br/>调到适合你的那一口。</h2><div className="sauce-console">{([['acid','酸度'],['salt','咸鲜'],['spice','辣感']] as const).map(([key,label])=><div key={key}><header><b>{label}</b><em>{sauce[key]}</em></header><input type="range" min="0" max="100" step="5" value={sauce[key]} onChange={e=>setSauce(c=>({...c,[key]:Number(e.target.value)}))}/><small>{key==='acid'?'番茄明亮度':key==='salt'?'酱汁厚度与鲜味':'入口后的刺激感'}</small></div>)}</div><div className="taste-clue"><span>你的Taste线索</span><p>{taste.spicy>65?'你通常接受更明确的辣感。':taste.healthy>65?'你偏清爽，调味不宜遮住食材。':'你更适合酸、咸、辣相对平衡。'}</p></div><button className="game-primary" onClick={()=>setPhase("plating")}>锁定味道</button></section>}
 {phase==="plating"&&<section className="game-stage">{progress(4)}<span className="game-kicker">05 / 出餐结构</span><h2>最后决定这盘菜<br/>看起来怎么吃。</h2><div className="plating-options mature-plating">{([['balanced','均衡分区','面、肉酱与蔬菜都能看见'],['heaped','高堆主食','份量感强，但结构被遮住'],['minimal','小份留白','克制，但可能不够饱']] as const).map(([v,n,d])=><button key={v} className={plating===v?"is-selected":""} onClick={()=>setPlating(v)}><i>{v==='balanced'?'A':v==='heaped'?'B':'C'}</i><span><b>{n}</b><small>{d}</small></span></button>)}</div><button className="game-primary" onClick={()=>setPhase("result")}>送上出餐口</button></section>}
 {phase==="result"&&<section className="game-result"><span className="game-kicker">KITCHEN REPORT</span><div className="score-ring"><strong>{score.total}</strong><small>/ 100</small></div><h1>{score.title}</h1><p>{score.total>=85?'完成度已经达到本关奖励线。真正拉开差距的是流程与火候。':'这次没有过奖励线。复盘最低的一项，再挑战会更有效。'}</p><div className="score-breakdown five"><span>食材<b>{score.ingredients}/20</b></span><span>顺序<b>{score.sequence}/20</b></span><span>火候<b>{score.heat}/25</b></span><span>调味<b>{score.seasoning}/20</b></span><span>装盘<b>{score.plating}/15</b></span></div>{score.couponEligible?<div className="game-coupon"><TicketPercent size={22}/><span><b>厨艺礼资格已解锁</b><small>正式兑换需通过服务器验分</small></span>{couponClaimed?<em>已领取</em>:<button onClick={onCoupon}>领取</button>}</div>:<div className="game-coupon is-locked"><TicketPercent size={22}/><span><b>距离奖励线还差 {85-score.total} 分</b><small>提升最低分项，比盲目重玩更有效</small></span></div>}<div className="game-share-actions"><button onClick={share}><Share2 size={17}/>发起好友挑战</button><button className={liked?"is-liked":""} onClick={()=>setLiked(true)}><Heart size={17} fill={liked?'currentColor':'none'}/>{liked?'已赞':'点赞'}</button></div><button className="game-retry" onClick={reset}><RotateCcw size={15}/>重新接受考核</button></section>}
 </main>
}
